import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Bedrock AG (Autonomous Governance) Documentation Sidebar
 *
 * This sidebar configuration uses autogeneration based on folder structure.
 * To add new sections:
 * 1. Create a new folder under docs/bedrock-ag/
 * 2. Add markdown files to the folder
 * 3. Use frontmatter 'sidebar_position' to control order
 */

const sidebars: SidebarsConfig = {
  bedrockAgSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '👋 Welcome',
    },
    {
      type: 'category',
      label: '🚀 Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started with Bedrock AG',
        description: 'Begin your autonomous governance journey.',
        keywords: ['getting started', 'setup', 'ai governance'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 User Guide',
      link: {
        type: 'generated-index',
        title: 'User Guide',
        description: 'Learn how to leverage Bedrock AG for automated governance.',
        keywords: ['user guide', 'governance', 'automation'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide',
        },
      ],
    },
    {
      type: 'category',
      label: '🤖 AI Features',
      link: {
        type: 'generated-index',
        title: 'AI-Powered Features',
        description: 'Explore intelligent governance capabilities.',
        keywords: ['ai', 'machine learning', 'automation'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-features',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 Integrations',
      link: {
        type: 'generated-index',
        title: 'Integrations',
        description: 'Connect Bedrock AG with your existing tools.',
        keywords: ['integrations', 'api', 'connectors'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
  ],
};

export default sidebars;
