import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Bedrock CMMC Documentation Sidebar
 *
 * This sidebar configuration uses autogeneration based on folder structure.
 * To add new sections:
 * 1. Create a new folder under docs/bedrock-cmmc/
 * 2. Add markdown files to the folder
 * 3. Use frontmatter 'sidebar_position' to control order
 *
 * Example frontmatter:
 * ---
 * sidebar_position: 1
 * title: My Document Title
 * ---
 */

const sidebars: SidebarsConfig = {
  // Main sidebar - automatically generated from folder structure
  bedrockCmmcSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '👋 Welcome',
    },
    {
      type: 'category',
      label: '🚀 Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Get up and running with Bedrock CMMC quickly and efficiently.',
        keywords: ['getting started', 'quick start', 'setup'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Installation',
      link: {
        type: 'generated-index',
        title: 'Installation & Deployment',
        description: 'Comprehensive installation guides for all deployment methods.',
        keywords: ['installation', 'deployment', 'setup'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'installation',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 User Guide',
      link: {
        type: 'generated-index',
        title: 'User Guide',
        description: 'Learn how to use Bedrock CMMC effectively.',
        keywords: ['user guide', 'how to', 'tutorial'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide',
        },
      ],
    },
    {
      type: 'category',
      label: '🔐 CMMC Controls',
      link: {
        type: 'generated-index',
        title: 'CMMC Controls Reference',
        description: 'Detailed information about CMMC practices and controls.',
        keywords: ['cmmc', 'controls', 'practices'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cmmc-controls',
        },
      ],
    },
    {
      type: 'category',
      label: '✓ Compliance',
      link: {
        type: 'generated-index',
        title: 'Compliance Features',
        description: 'Maintain and demonstrate CMMC compliance.',
        keywords: ['compliance', 'audit', 'certification'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'compliance',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 API Reference',
      link: {
        type: 'generated-index',
        title: 'API Documentation',
        description: 'RESTful API reference for Bedrock CMMC.',
        keywords: ['api', 'rest', 'integration'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 Troubleshooting',
      link: {
        type: 'generated-index',
        title: 'Troubleshooting Guide',
        description: 'Common issues and solutions.',
        keywords: ['troubleshooting', 'problems', 'solutions', 'faq'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'troubleshooting',
        },
      ],
    },
  ],
};

export default sidebars;
