import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Bedrock SP (Security Platform) Documentation Sidebar
 *
 * This sidebar configuration uses autogeneration based on folder structure.
 * To add new sections:
 * 1. Create a new folder under docs/bedrock-sp/
 * 2. Add markdown files to the folder
 * 3. Use frontmatter 'sidebar_position' to control order
 */

const sidebars: SidebarsConfig = {
  bedrockSpSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '👋 Welcome',
    },
    {
      type: 'category',
      label: '🚀 Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started with Bedrock SP',
        description: 'Set up your security operations platform.',
        keywords: ['getting started', 'siem', 'soc'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 User Guide',
      link: {
        type: 'generated-index',
        title: 'User Guide',
        description: 'Master your security operations with Bedrock SP.',
        keywords: ['user guide', 'security operations', 'soc'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-guide',
        },
      ],
    },
    {
      type: 'category',
      label: '🔍 Threat Hunting',
      link: {
        type: 'generated-index',
        title: 'Threat Hunting',
        description: 'Proactive threat detection and hunting.',
        keywords: ['threat hunting', 'detection', 'analysis'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'threat-hunting',
        },
      ],
    },
    {
      type: 'category',
      label: '🚨 Incident Response',
      link: {
        type: 'generated-index',
        title: 'Incident Response',
        description: 'Respond to and manage security incidents.',
        keywords: ['incident response', 'playbooks', 'soar'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'incident-response',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 Integrations',
      link: {
        type: 'generated-index',
        title: 'Integrations',
        description: 'Connect your security tools to Bedrock SP.',
        keywords: ['integrations', 'connectors', 'api'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
  ],
};

export default sidebars;
