/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Foxx Cyber Documentation",
  "tagline": "Comprehensive guides and documentation for Foxx Cyber security solutions",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://docs.foxxcyber.com",
  "baseUrl": "/",
  "organizationName": "foxxcyber",
  "projectName": "docs",
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownImages": "warn",
      "onBrokenMarkdownLinks": "warn"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "docs/bedrock-cmmc",
          "routeBasePath": "bedrock-cmmc",
          "sidebarPath": "./sidebars-bedrock-cmmc.ts",
          "editUrl": "https://github.com/foxxcyber/docs/tree/main/"
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/foxxcyber/docs/tree/main/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "bedrock-ag",
        "path": "docs/bedrock-ag",
        "routeBasePath": "bedrock-ag",
        "sidebarPath": "./sidebars-bedrock-ag.ts",
        "editUrl": "https://github.com/foxxcyber/docs/tree/main/"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "bedrock-sp",
        "path": "docs/bedrock-sp",
        "routeBasePath": "bedrock-sp",
        "sidebarPath": "./sidebars-bedrock-sp.ts",
        "editUrl": "https://github.com/foxxcyber/docs/tree/main/"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "Foxx Cyber",
      "logo": {
        "alt": "Foxx Cyber Logo",
        "src": "img/foxx-cyber-logo.png"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "Products",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "intro",
              "label": "Bedrock CMMC",
              "docsPluginId": "default"
            },
            {
              "type": "doc",
              "docId": "intro",
              "label": "Bedrock AG",
              "docsPluginId": "bedrock-ag"
            },
            {
              "type": "doc",
              "docId": "intro",
              "label": "Bedrock SP",
              "docsPluginId": "bedrock-sp"
            }
          ]
        },
        {
          "to": "/blog",
          "label": "Release Notes",
          "position": "left"
        },
        {
          "href": "https://foxxcyber.com",
          "label": "Foxx Cyber",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Products",
          "items": [
            {
              "label": "Bedrock CMMC",
              "to": "/bedrock-cmmc/intro"
            },
            {
              "label": "Bedrock AG",
              "to": "/bedrock-ag/intro"
            },
            {
              "label": "Bedrock SP",
              "to": "/bedrock-sp/intro"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Release Notes",
              "to": "/blog"
            },
            {
              "label": "Support",
              "href": "https://foxxcyber.com/support"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "Website",
              "href": "https://foxxcyber.com"
            },
            {
              "label": "Contact",
              "href": "https://foxxcyber.com/contact"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Foxx Cyber LLC. All rights reserved."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
